### PR TITLE
Advertize node versions support

### PR DESCRIPTION
**Pull request by NSeydoux**
Not a critically necessary change, as by nature this library supported Node 18 from the start, but it's nice to have explicit support marked, so that we have a warning if we try to install this in an untested version (looking at Node 20 coming soon)

### CODE REVIEW

**Comment by jeswr** [comment]
@NSeydoux I don't think we should make this change:
1. It will introduce an unnecessary warning for users trying to use this on odd versions of node
2. It introduces maintenance burden for us to immediately update the engines field for each new version of Node. I think we can be confident `fetch` will be available in Node 20 given that it is available in Node 19.

**Comment by NSeydoux** [comment]
Odd versions of Node are active development versions, and as per our policy we don't support them, so warning our users about it is a matter of transparency. And I don't doubt that this will be compatible with Node 20, however we should test that it works properly and then mark our support, and not the other way around assuming things will work and them potentially breaking without a warning from our libraries.

**Review by jeswr — APPROVED** [review]

**Comment by jeswr** [comment]
I've added node 20 support in the engine as well now @NSeydoux

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Pull request merged**
