### PR TITLE
chore: add pre-releasing support to workflows

### PR DESCRIPTION
**Pull request by jeswr**
Once this is merged we can create pre-releases by

1. Creating a new version `npm version pre[patch|minor|major] --preid [alpha|beta]` in a PR
2. Merging that to main
3. Create a new github tag & release with the same version number that gets created in (1) which will be of the format `v[0-9]+.[0-9]+.[0-9]+-[alpha|beta].[0-9]+`. Make sure we set this to be a pre-release in the GH UI.

These instruction need a better home long term, but I want to try and automate some of them first once we have agreement on the general approach.

### CODE REVIEW

**Comment by chelseapinka** [comment]
I almost wonder if it is worth adding a `npm run pre-release` similar to https://github.com/inrupt/typescript-sdk-tools/blob/main/scripts/prepare-release.sh just so we don't have accidental misses on spelling/typing the release versions.

**Comment by chelseapinka** [comment]
> Once this is merged we can create pre-releases by
> 
> 1. Creating a new version `npm version pre[patch|minor|major] --preid [alpha|beta]` in a PR
> 2. Merging that to main

So essentially this is just allowing alpha/beta versions to be published, but similiar to other repos, including this one, all releases will still be a separate PR than the PR with the code changes?

**Comment by NSeydoux** [comment]
> So essentially this is just allowing alpha/beta versions to be published, but similiar to other repos, including this one, all releases will still be a separate PR than the PR with the code changes?

Not necessarily I don't think: what triggers CD is a tag being pushed. The CD checks out the tagged commit, but there is no requirement that this commit is in main, so I think publishing directly from the feature branch would be possible.

**Comment by jeswr** [comment]
> So essentially this is just allowing alpha/beta versions to be published, but similiar to other repos, including this one, all releases will still be a separate PR than the PR with the code changes?

It could be done this way. Is Nick says "publishing directly from the feature branch would be possible."; noting that we could also do this for normal releases if we wanted because those are also published off a git tag.

So the question really is do we want to make our beta release by just cutting a release in the GitHub UI targeting https://github.com/inrupt/universal-fetch/pull/293 as a branch. Or do we want to merge that branch into main and then cut a beta release in the UI.

**Comment by jeswr** [comment]
> I almost wonder if it is worth adding a npm run pre-release similar to https://github.com/inrupt/typescript-sdk-tools/blob/main/scripts/prepare-release.sh just so we don't have accidental misses on spelling/typing the release versions.

I agree, this is kind of what I meant by "I want to try and automate some of them first once we have agreement on the general approach." I suggest can do this in a follow up PR.

**Review by chelseapinka — APPROVED** [review]
Makes sense to try this and then see if this what improvements to layer on.

**Pull request merged**
