### PR TITLE
Initial version of library

### PR DESCRIPTION
**Pull request by jeswr**
# New feature description

This is the first version of `@inrupt/universal-fetch`. I expect that the library should be ready for release after this PR is merged.

# Checklist

- [x] All acceptance criteria are met.
- [x] Relevant documentation, if any, has been written/updated.
- [x] The changelog has been updated, if applicable.
- [x] New functions/types have been exported in `index.ts`, if applicable.
- [x] New modules (i.e. new `.ts` files) are listed in the `exports` field in `package.json`, if applicable.
- [x] New modules (i.e. new `.ts` files) are listed in the `typedocOptions.entryPoints` field in `tsconfig.json`, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by ThisIsMissEm — CHANGES_REQUESTED** [review]
There's a lot in here, the initial implementation looks okay, but there's also some things to improve

**Review by ThisIsMissEm — CHANGES_REQUESTED** [review]
If you're going to remove the e2e tests, then you should also remove the `e2e-node.yml` and `e2e-browser.yml` files, otherwise we'll need to add e2e tests back in, which will be some work. 

I'm okay with e2e tests being removed entirely for the first iteration, we can add them back in once we've proved the concept (it's not like this won't have coverage, it will by downstream consumers' e2e tests)

**Review by ThisIsMissEm — CHANGES_REQUESTED** [review]
Still a bunch of changes, sorry, was tired the last time I reviewed and didn't catch everything

**Review by NSeydoux — APPROVED** [review]

**Review by ThisIsMissEm — APPROVED** [review]
I think we're now good on this, I did go through and add some additional changes:

https://github.com/inrupt/universal-fetch/pull/20/files/90672d530ba50e8b219cc31ce9c3477f964c274f..de9e15b5a0f72ae9e7519ea30399b42db16b3606

**Pull request closed without merging**
